"""add safety_status and location_hierarchy_json to ods_crags

Revision ID: 0491aac1cafc
Revises: 40870637c7e6
Create Date: 2025-03-24 22:24:31.705102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0491aac1cafc'
down_revision: Union[str, None] = '40870637c7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ods_crags', sa.Column('url', sa.String(length=255), nullable=False))
    op.add_column('ods_crags', sa.Column('location_hierarchy_json', sa.JSON(), nullable=True))
    op.add_column('ods_crags', sa.Column('safety_status', sa.Enum('SAFE', 'CAUTION', 'UNSAFE', name='safetystatus'), nullable=False))
    op.drop_column('ods_crags', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ods_crags', sa.Column('location', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('ods_crags', 'safety_status')
    op.drop_column('ods_crags', 'location_hierarchy_json')
    op.drop_column('ods_crags', 'url')
    # ### end Alembic commands ###
