"""create area_nodes table

Revision ID: 40870637c7e6
Revises: eb4596022f60
Create Date: 2025-03-24 21:12:32.668034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40870637c7e6'
down_revision: Union[str, None] = 'eb4596022f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ods_crags',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ods_precipitation',
    sa.Column('crag_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recorded_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('precipitation_mm', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['crag_id'], ['ods_crags.id'], ),
    sa.PrimaryKeyConstraint('crag_id', 'recorded_at')
    )
    op.drop_index('url', table_name='area_nodes')
    op.drop_table('area_nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_nodes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parent_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('google_maps_url', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('url', 'area_nodes', ['url'], unique=True)
    op.drop_table('ods_precipitation')
    op.drop_table('ods_crags')
    # ### end Alembic commands ###
