"""create area_nodes table

Revision ID: eb4596022f60
Revises: 
Create Date: 2025-03-24 20:44:37.807294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb4596022f60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('parent_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('crag_precipitation_hourly')
    op.drop_table('crag_precipitation_daily')
    op.drop_table('crags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crags',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('longitude', mysql.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('safety_status', mysql.ENUM('SAFE', 'CAUTION', 'UNSAFE'), nullable=False),
    sa.Column('last_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('crag_precipitation_daily',
    sa.Column('crag_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recorded_date', sa.DATE(), nullable=False),
    sa.Column('precipitation_mm', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('crag_id', 'recorded_date'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('crag_precipitation_hourly',
    sa.Column('crag_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recorded_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('precipitation_mm', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('crag_id', 'recorded_at'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('area_nodes')
    # ### end Alembic commands ###
